#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>

int main() {
    int server_socket, client_socket;
    struct sockaddr_in server_address;
    char request_buffer[4096];

    server_socket = socket(AF_INET, SOCK_STREAM, 0);

    if (server_socket < 0) {
        printf("Error: Could not create socket!\n");
        return 1;
    }
    printf("✓ Socket created successfully\n");

    server_address.sin_family = AF_INET;
    server_address.sin_addr.s_addr = INADDR_ANY;
    server_address.sin_port = htons(8080);

    int bind_result = bind(server_socket,
                           (struct sockaddr*)&server_address,
                           sizeof(server_address));

    if (bind_result < 0) {
        printf("Error: Could not bind to port 8080!\n");
        return 1;
    }
    printf("✓ Socket bound to port 8080\n");

    int listen_result = listen(server_socket, 10);

    if (listen_result < 0) {
        printf("Error: Could not listen on socket!\n");
        return 1;
    }
 
    printf("\n========================================\n");
    printf(" Server is running!\n");
    printf("========================================\n");
    printf("Visit: http://localhost:8080\n");
    printf("Waiting for a connection...\n\n");
 
    client_socket = accept(server_socket, NULL, NULL);

    if (client_socket < 0) {
        printf("Error: Could not accept connection!\n");
        return 1;
    }
    printf("✓ Client connected!\n");

    int bytes_read = read(client_socket, request_buffer, sizeof(request_buffer) - 1);
    request_buffer[bytes_read] = '\0';
 
    printf("\n--- HTTP Request Received ---\n");
    printf("%s\n", request_buffer);
    printf("-----------------------------\n\n");

    char *http_response =
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "Connection: close\r\n"
        "\r\n"
        "<html>"
        "<head><title>C Server</title></head>"
        "<body>"
        "<h1>Hello from C server!</h1>"
        "<p>This response was generated by a simple C program.</p>"
        "</body>"
        "</html>";
 
    int bytes_sent = write(client_socket, http_response, strlen(http_response));
 
    printf("✓ Sent %d bytes to client\n", bytes_sent);
    printf("✓ Response delivered successfully!\n\n");
 
    close(client_socket);
    close(server_socket);

    printf("Server shut down gracefully.\n");

    return 0;
}
